//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nFrickBoard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// key.txtのキー表記とアスキーコードの対応定義
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("key.txtのキー表記とアスキーコードの対応定義")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>BackSpace 08</string>\r\n  <string>TAB 09</string>\r\n  <string>Shift 10</stri" +
            "ng>\r\n  <string>Ctrl 11</string>\r\n  <string>Alt 12</string>\r\n  <string>Esc 1B</st" +
            "ring>\r\n  <string>Space 20</string>\r\n  <string>PageUp 21</string>\r\n  <string>Page" +
            "Down 22</string>\r\n  <string>End 23</string>\r\n  <string>Home 24</string>\r\n  <stri" +
            "ng>← 25</string>\r\n  <string>↑ 26</string>\r\n  <string>→ 27</string>\r\n  <string>↓ " +
            "28</string>\r\n  <string>Ins 2D</string>\r\n  <string>Delete 2E</string>\r\n  <string>" +
            "num0 60</string>\r\n  <string>num1 61</string>\r\n  <string>num2 62</string>\r\n  <str" +
            "ing>num3 63</string>\r\n  <string>num4 64</string>\r\n  <string>num5 65</string>\r\n  " +
            "<string>num6 66</string>\r\n  <string>num7 67</string>\r\n  <string>num8 68</string>" +
            "\r\n  <string>num9 69</string>\r\n  <string>num* 6A</string>\r\n  <string>num+ 6B</str" +
            "ing>\r\n  <string>num- 6D</string>\r\n  <string>num/ 6F</string>\r\n  <string>F1 70</s" +
            "tring>\r\n  <string>F2 71</string>\r\n  <string>F3 72</string>\r\n  <string>F4 73</str" +
            "ing>\r\n  <string>F5 74</string>\r\n  <string>F6 75</string>\r\n  <string>F7 76</strin" +
            "g>\r\n  <string>F8 77</string>\r\n  <string>F9 78</string>\r\n  <string>F10 79</string" +
            ">\r\n  <string>F11 7A</string>\r\n  <string>F12 7B</string>\r\n  <string>: BA</string>" +
            "\r\n  <string>; BB</string>\r\n  <string>, BC</string>\r\n  <string>- BD</string>\r\n  <" +
            "string>. BE</string>\r\n  <string>/ BF</string>\r\n  <string>@ C0</string>\r\n  <strin" +
            "g>[ DB</string>\r\n  <string>] DD</string>\r\n  <string>^ DE</string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection KeyDef {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyDef"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ホイール</string>
  <string>ブラシ濃度</string>
  <string>ブラシサイズ</string>
  <string>PS不透明度</string>
  <string>レイヤー不透明度</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection padStr {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["padStr"]));
            }
            set {
                this["padStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Ctrl + Alt + Shift + 1 </string>
  <string>Ctrl + Alt + Shift + 3</string>
  <string>Ctrl + Alt + Shift + 5 </string>
  <string>Ctrl + Alt + Shift + 7</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection padCD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["padCD"]));
            }
            set {
                this["padCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Ctrl + Alt + Shift + 2</string>
  <string>Ctrl + Alt + Shift + 4</string>
  <string>Ctrl + Alt + Shift + 6</string>
  <string>Ctrl + Alt + Shift + 8</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection padCDR {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["padCDR"]));
            }
            set {
                this["padCDR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>取り消し</string>
  <string>貼り付け</string>
  <string>コピー</string>
  <string>切り取り</string>
  <string>やり直し</string>
  <string>ブラシツール</string>
  <string>手のひらツール</string>
  <string>バケツツール</string>
  <string>移動ツール</string>
  <string>消しゴムツール</string>
  <string>全体表示 0°</string>
  <string>ズームイン</string>
  <string>ズームアウト</string>
  <string>回転ツール</string>
  <string>左右反転</string>
  <string>自動選択ツール</string>
  <string>選択解除</string>
  <string>投げ縄ツール</string>
  <string>消去</string>
  <string>すべて選択</string>
  <string>新規レイヤー</string>
  <string>レイヤーを削除</string>
  <string>乾燥</string>
  <string>下のレイヤーと結合</string>
  <string>レイヤーを複製</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeyStr {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyStr"]));
            }
            set {
                this["KeyStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Ctrl + Z </string>
  <string>Ctrl + V </string>
  <string>Ctrl + C </string>
  <string>Ctrl + X </string>
  <string>Ctrl + Shift + Z </string>
  <string>B </string>
  <string>num2</string>
  <string>K </string>
  <string>num4</string>
  <string>E</string>
  <string>Home </string>
  <string>PageUp </string>
  <string>PageDown </string>
  <string>R </string>
  <string>H </string>
  <string>W </string>
  <string>Ctrl + D </string>
  <string>L </string>
  <string>Delete </string>
  <string>Ctrl + A </string>
  <string>Ctrl + Shift + N </string>
  <string>Shift + N </string>
  <string>A </string>
  <string>Ctrl + E </string>
  <string>Ctrl + J </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeyCD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyCD"]));
            }
            set {
                this["KeyCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>編集</string>
  <string>ツール</string>
  <string>表示</string>
  <string>選択</string>
  <string>レイヤー</string>
  <string>修飾キー</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BtnTXT {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BtnTXT"]));
            }
            set {
                this["BtnTXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ButtonCnt {
            get {
                return ((int)(this["ButtonCnt"]));
            }
            set {
                this["ButtonCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PadCnt {
            get {
                return ((int)(this["PadCnt"]));
            }
            set {
                this["PadCnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FrickRange {
            get {
                return ((int)(this["FrickRange"]));
            }
            set {
                this["FrickRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int CancelRange {
            get {
                return ((int)(this["CancelRange"]));
            }
            set {
                this["CancelRange"] = value;
            }
        }
        
        /// <summary>
        /// nekopaint本体ディレクトリ
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("nekopaint本体ディレクトリ")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string npDir {
            get {
                return ((string)(this["npDir"]));
            }
            set {
                this["npDir"] = value;
            }
        }
        
        /// <summary>
        /// nekopaint全ショートカット
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("nekopaint全ショートカット")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ファイル 513 新規作成...</string>\r\n  <string>ファイル 514 開く...</string>\r\n  <string>ファ" +
            "イル 515 保存</string>\r\n  <string>ファイル 516 名前を付けて保存...</string>\r\n  <string>ファイル 518 " +
            "web用に保存</string>\r\n  <string>ファイル 520 閉じる</string>\r\n  <string>ファイル 529 環境設定</stri" +
            "ng>\r\n  <string>ファイル 530 次のページ</string>\r\n  <string>ファイル 531 前のページ</string>\r\n  <st" +
            "ring>ヘルプ 532 ヘルプ→保存</string>\r\n  <string>ファイル 544 終了</string>\r\n  <string>編集 769 取" +
            "り消し</string>\r\n  <string>編集 770 やり直し</string>\r\n  <string>編集 771 メモリ開放</string>\r\n " +
            " <string>編集 778 塗りつぶし</string>\r\n  <string>編集 785 コピー</string>\r\n  <string>編集 786 " +
            "切り取り</string>\r\n  <string>編集 787 貼り付け</string>\r\n  <string>編集 788 消去</string>\r\n  <" +
            "string>編集 790 ※1pxごとに上に移動</string>\r\n  <string>編集 791 ※1pxごとに下に移動</string>\r\n  <st" +
            "ring>編集 792 ※1pxごとに左に移動</string>\r\n  <string>編集 793 ※1pxごとに右に移動</string>\r\n  <stri" +
            "ng>編集 804 変形 拡大縮小回転</string>\r\n  <string>編集 805 貼り付け 透明度付き</string>\r\n  <string>編集" +
            " 806 コピー 透明度付き</string>\r\n  <string>イメージ 1025 キャンバスサイズ</string>\r\n  <string>イメージ 1" +
            "026 色調補正 トーンカーブ HSV</string>\r\n  <string>イメージ 1027 色調補正 トーンカーブ HSV</string>\r\n  <s" +
            "tring>イメージ 1028 選択範囲でキャンバスをトリミング</string>\r\n  <string>レイヤー 1281 新規レイヤー</string>\r\n" +
            "  <string>レイヤー 1282 レイヤーを複製</string>\r\n  <string>レイヤー 1283 レイヤーを削除</string>\r\n  <s" +
            "tring>レイヤー 1284 下のレイヤーと結合</string>\r\n  <string>ヘルプ 1285 ヘルプ→新規ベクタレイヤ（仮置き）</string" +
            ">\r\n  <string>レイヤー 1287 新規ベクタレイヤ（test）</string>\r\n  <string>レイヤー 1290 レイヤー消去</stri" +
            "ng>\r\n  <string>レイヤー 1296 線画抽出</string>\r\n  <string>レイヤー 1297 レイヤー→左右反転</string>\r\n" +
            "  <string>レイヤー 1298 レイヤー→上下反転</string>\r\n  <string>レイヤー 1299 新規レイヤー(1bit)</string" +
            ">\r\n  <string>レイヤー 1300 新規レイヤー(8bit)</string>\r\n  <string>レイヤー 1302 レイヤー色変更</strin" +
            "g>\r\n  <string>レイヤー 1303 フォルダを複製</string>\r\n  <string>レイヤー 1304 フォルダを複製(表示レイヤーのみ)<" +
            "/string>\r\n  <string>レイヤー 1312 下のレイヤーとグループ化</string>\r\n  <string>レイヤー 1313 グループ解除<" +
            "/string>\r\n  <string>レイヤー 1335 レイヤーを保存</string>\r\n  <string>レイヤー 1336 現在のレイヤーのみ表示<" +
            "/string>\r\n  <string>レイヤー 1337 新規グループ</string>\r\n  <string>レイヤー 1344 ベクターレイヤー読み込み<" +
            "/string>\r\n  <string>レイヤー 1345 ベクターレイヤー保存</string>\r\n  <string>α 1360 下のレイヤー</stri" +
            "ng>\r\n  <string>α 1361 上のレイヤー</string>\r\n  <string>レイヤー 1362 乾燥</string>\r\n  <strin" +
            "g>レイヤー 1392 編集 レイヤーマスク</string>\r\n  <string>選択範囲 1537 すべて選択</string>\r\n  <string>選" +
            "択範囲 1538 選択解除</string>\r\n  <string>選択範囲 1539 選択範囲を反転</string>\r\n  <string>選択範囲 155" +
            "2 選択範囲を拡張</string>\r\n  <string>選択範囲 1553 選択範囲を縮小</string>\r\n  <string>選択範囲 1555 選択" +
            "範囲表示</string>\r\n  <string>選択範囲 1584 選択範囲を拡張1pixel</string>\r\n  <string>選択範囲 1585 選" +
            "択範囲を縮小1pixel</string>\r\n  <string>ブラシ 2305 サンプル 猫ペン4 補正弱</string>\r\n  <string>ブラシ " +
            "2306 サンプル 猫ペン4</string>\r\n  <string>ビュー 2817 新規ビュー</string>\r\n  <string>ビュー 2818 左" +
            "右反転ビュー</string>\r\n  <string>ビュー 2819 新規タブ</string>\r\n  <string>ビュー 2821 新規タブ2</str" +
            "ing>\r\n  <string>ビュー 2834 ズームイン</string>\r\n  <string>ビュー 2835 ズームアウト</string>\r\n  <" +
            "string>ビュー 2836 等倍</string>\r\n  <string>ビュー 2837 全体表示</string>\r\n  <string>ビュー 283" +
            "8 全体表示 0°</string>\r\n  <string>ビュー 2839 回転リセット</string>\r\n  <string>ビュー 2840 カーソルを" +
            "中心にズームイン</string>\r\n  <string>ビュー 2841 カーソルを中心にズームアウト</string>\r\n  <string>ビュー 284" +
            "8 左右反転</string>\r\n  <string>ビュー 2849 上下反転</string>\r\n  <string>ビュー 2850 キャンバス アンチエ" +
            "イリアス ON/OFF</string>\r\n  <string>ビュー 2851 次のビュー</string>\r\n  <string>ビュー 2852 定規</" +
            "string>\r\n  <string>ビュー 2853 定規 軸変更</string>\r\n  <string>ビュー 2854 キャンバス 高画質 ON/OFF" +
            "</string>\r\n  <string>ビュー 2855 キャンバス 高画質2 ON/OFF</string>\r\n  <string>ビュー 2856 カーソ" +
            "ルを中心に左右反転</string>\r\n  <string>ビュー 2857 カーソルを中心に上下反転</string>\r\n  <string>ビュー 2864" +
            " スクロール ←</string>\r\n  <string>ビュー 2865 スクロール →</string>\r\n  <string>ビュー 2866 スクロール" +
            " ↑</string>\r\n  <string>ビュー 2867 スクロール ↓</string>\r\n  <string>ビュー 2880 回転 CW</stri" +
            "ng>\r\n  <string>ビュー 2881 回転 CCW</string>\r\n  <string>ビュー 2882 回転 大 CW</string>\r\n  " +
            "<string>ビュー 2883 回転 大 CCW</string>\r\n  <string>ビュー 2884 カーソルを中心に回転 CW</string>\r\n " +
            " <string>ビュー 2885 カーソルを中心に回転 CCW</string>\r\n  <string>ビュー 2886 カーソルを中心に回転 大 CW</s" +
            "tring>\r\n  <string>ビュー 2887 カーソルを中心に回転 大 CCW</string>\r\n  <string>ビュー 2888 カーソルを中心" +
            "に180°回転</string>\r\n  <string>ビュー 2896 回転対称 中心</string>\r\n  <string>ビュー 2897 左右対称 軸" +
            "</string>\r\n  <string>ビュー 2898 カーソルの位置を回転対称の中心に設定</string>\r\n  <string>ビュー 2899 カー" +
            "ソルの位置を左右対称の軸に設定</string>\r\n  <string>ビュー 2913 読み込み 消失点1</string>\r\n  <string>ビュー 2" +
            "914 読み込み 消失点2</string>\r\n  <string>ビュー 2915 読み込み 消失点3</string>\r\n  <string>ビュー 291" +
            "6 読み込み 消失点4</string>\r\n  <string>ビュー 2917 読み込み 消失点5</string>\r\n  <string>ビュー 2918 " +
            "読み込み 消失点6</string>\r\n  <string>ビュー 2929 保存 消失点1</string>\r\n  <string>ビュー 2930 保存 消" +
            "失点2</string>\r\n  <string>ビュー 2931 保存 消失点3</string>\r\n  <string>ビュー 2932 保存 消失点4</s" +
            "tring>\r\n  <string>ビュー 2933 保存 消失点5</string>\r\n  <string>ビュー 2934 保存 消失点6</string>" +
            "\r\n  <string>ツール 3073 ブラシツール</string>\r\n  <string>ツール 3074 消しゴムツール</string>\r\n  <st" +
            "ring>ツール 3075 選択ブラシツール</string>\r\n  <string>ツール 3076 選択消しゴムツール</string>\r\n  <strin" +
            "g>ツール 3088 スポイトツール</string>\r\n  <string>ツール 3104 バケツツール</string>\r\n  <string>ツール 3" +
            "105 自動選択ツール</string>\r\n  <string>ツール 3106 投げ縄ツール</string>\r\n  <string>ツール 3107 矩形選" +
            "択ツール</string>\r\n  <string>ツール 3108 グラデーションツール</string>\r\n  <string>ツール 3120 手のひらツー" +
            "ル</string>\r\n  <string>ツール 3121 ズームツール</string>\r\n  <string>ツール 3122 回転ツール</string" +
            ">\r\n  <string>ツール 3136 移動ツール</string>\r\n  <string>ツール 3168 コマ割りガイドツール</string>\r\n  " +
            "<string>ツール 3233 ブラシ フリーハンド</string>\r\n  <string>ツール 3234 ブラシ 直線</string>\r\n  <str" +
            "ing>ツール 3235 ブラシ 連続直線</string>\r\n  <string>ツール 3236 ブラシ 曲線</string>\r\n  <string>ツー" +
            "ル 3237 ブラシ 楕円</string>\r\n  <string>ツール 3238 ブラシ 矩形</string>\r\n  <string>ウィンドウ 3329" +
            " ブラシ表示切り替え</string>\r\n  <string>ウィンドウ 3330 レイヤー表示切り替え</string>\r\n  <string>ウィンドウ 3" +
            "331 色表示切り替え</string>\r\n  <string>ウィンドウ 3332 ナビゲーター表示切り替え</string>\r\n  <string>ウィンド" +
            "ウ 3334 ※全ウィンドウの表示非表示(現在のtab)</string>\r\n  <string>ウィンドウ 3335 ブラシセット表示切り替え</string" +
            ">\r\n  <string>ウィンドウ 3336 ツールオプション</string>\r\n  <string>ウィンドウ 3337 ※表示ウィンドウと非表示ウィンド" +
            "ウを切替（ドッキングパレット除く）</string>\r\n  <string>ウィンドウ 3345 custom1表示切り替え</string>\r\n  <stri" +
            "ng>ウィンドウ 3346 custom2表示切り替え</string>\r\n  <string>ウィンドウ 3347 custom3表示切り替え</string" +
            ">\r\n  <string>ウィンドウ 3348 custom4表示切り替え</string>\r\n  <string>ウィンドウ 3354 ベクター筆圧</str" +
            "ing>\r\n  <string>ウィンドウ 3355 パネル1</string>\r\n  <string>ウィンドウ 3356 パネル2</string>\r\n  " +
            "<string>ウィンドウ 3360 カスタム作成</string>\r\n  <string>ウィンドウ 3361 key設定表示</string>\r\n  <st" +
            "ring>ウィンドウ 3368 レイヤービュー</string>\r\n  <string>ウィンドウ 3369 レイヤービュー左右反転</string>\r\n  <" +
            "string>ウィンドウ 3377 レイアウト保存1</string>\r\n  <string>ウィンドウ 3378 レイアウト保存2</string>\r\n  <" +
            "string>ウィンドウ 3379 レイアウト保存3</string>\r\n  <string>ウィンドウ 3380 レイアウト保存4</string>\r\n  <" +
            "string>ウィンドウ 3393 レイアウト読み込み1</string>\r\n  <string>ウィンドウ 3394 レイアウト読み込み2</string>\r" +
            "\n  <string>ウィンドウ 3395 レイアウト読み込み3</string>\r\n  <string>ウィンドウ 3396 レイアウト読み込み4</stri" +
            "ng>\r\n  <string>ウィンドウ 3424 ツールボックス→サイズ</string>\r\n  <string>ウィンドウ 3425 ツールボックス→色</" +
            "string>\r\n  <string>ウィンドウ 3426 ツールボックス→方向</string>\r\n  <string>ウィンドウ 3440 パネル1→色</" +
            "string>\r\n  <string>ウィンドウ 3441 パネル1→ブラシ1</string>\r\n  <string>ウィンドウ 3442 パネル1→ブラシ2" +
            "</string>\r\n  <string>ファイル 3450 タブ</string>\r\n  <string>ファイル 3456 スタート</string>\r\n " +
            " <string>ファイル 3457 レイアウト</string>\r\n  <string>ヘルプ 3600 バージョン情報</string>\r\n  <strin" +
            "g>ヘルプ 3602 登録</string>\r\n  <string>ブラシ 4113 ブラシサイズ 拡大</string>\r\n  <string>ブラシ 411" +
            "4 ブラシサイズ 縮小</string>\r\n  <string>α 4115 hsvコントロール切り替え</string>\r\n  <string>ツール 412" +
            "0 スポイト 背景色 スクリーン</string>\r\n  <string>ツール 4121 スポイト 背景色 アクティブレイヤ</string>\r\n  <str" +
            "ing>ツール 4129 描画色・背景色切り替え</string>\r\n  <string>ツール 4130 スポイト スクリーン</string>\r\n  <st" +
            "ring>ツール 4131 描画色を黒・背景色を白に変更</string>\r\n  <string>α 4134 ツールボックス幅+1</string>\r\n  <" +
            "string>α 4135 ツールボックス幅-1</string>\r\n  <string>α 4136 hsvコントロール反転</string>\r\n  <str" +
            "ing>ツール 4137 スポイト アクティブレイヤ</string>\r\n  <string>ブラシ 4145 ブラシ濃度10%</string>\r\n  <st" +
            "ring>ブラシ 4146 ブラシ濃度20%</string>\r\n  <string>ブラシ 4147 ブラシ濃度30%</string>\r\n  <string" +
            ">ブラシ 4148 ブラシ濃度40%</string>\r\n  <string>ブラシ 4149 ブラシ濃度50%</string>\r\n  <string>ブラシ" +
            " 4150 ブラシ濃度60%</string>\r\n  <string>ブラシ 4151 ブラシ濃度70%</string>\r\n  <string>ブラシ 415" +
            "2 ブラシ濃度80%</string>\r\n  <string>ブラシ 4153 ブラシ濃度90%</string>\r\n  <string>ブラシ 4160 ブラ" +
            "シ濃度100%</string>\r\n  <string>ツール 4176 透明色切り替え</string>\r\n  <string>ツール 4177 前景色 背景" +
            "色 リンク</string>\r\n  <string>α 4178 連動 H</string>\r\n  <string>α 4179 連動 S</string>\r\n" +
            "  <string>α 4180 連動 V</string>\r\n  <string>α 4181 マルチタッチ風手のひらツール</string>\r\n  <str" +
            "ing>ツール 4186 ベクター 自動選択解除ON/OFF</string>\r\n  <string>α 4192 分割切り抜き</string>\r\n  <st" +
            "ring>α 4193 分割なし</string>\r\n  <string>α 4194 分割 2x2</string>\r\n  <string>α 4195 分割" +
            " 4x4</string>\r\n  <string>α 4196 分割 4x4 B</string>\r\n  <string>α 4200 着せ替え書き出し</st" +
            "ring>\r\n  <string>ブラシ 4208 猫補正　品質を有効</string>\r\n  <string>ブラシ 4209 猫補正 品質 低</strin" +
            "g>\r\n  <string>ブラシ 4213 猫補正 品質 中</string>\r\n  <string>ブラシ 4218 猫補正 品質 高</string>\r\n" +
            "  <string>α 4225 α→temp dir</string>\r\n  <string>α 4226 線消しゴムを使用する</string>\r\n  <s" +
            "tring>α 4227 ブラシをスタンプ風に利用する</string>\r\n  <string>α 4229 コマ割りガイド削除</string>\r\n  <st" +
            "ring>ブラシ 4240 ブラシ設定 保存</string>\r\n  <string>ブラシ 4241 ブラシ設定 読み込み</string>\r\n  <stri" +
            "ng>ブラシ 4242 ブラシ設定を貼り付け</string>\r\n  <string>ブラシ 4243 ブラシ設定をコピー</string>\r\n  <strin" +
            "g>ブラシ 4256 ブラシ 筆圧 ジッター</string>\r\n  <string>ブラシ 4257 ブラシ 筆圧 格子</string>\r\n  <strin" +
            "g>ブラシ 4258 ブラシ 筆圧 補充</string>\r\n  <string>ブラシ 4259 ブラシ 筆圧 間隔</string>\r\n  <string>" +
            "ブラシ 4272 ブラシ レイヤー透明度 ジッター</string>\r\n  <string>α 4288 自動保存→なし</string>\r\n  <string" +
            ">α 4289 自動保存→5分</string>\r\n  <string>α 4290 自動保存→10分</string>\r\n  <string>α 4291 自" +
            "動保存→15分</string>\r\n  <string>α 4292 自動保存→20分</string>\r\n  <string>ツール 4298 ツール一時切り" +
            "替え→なし</string>\r\n  <string>ツール 4299 ツール一時切り替え→300</string>\r\n  <string>ツール 4300 ツー" +
            "ル一時切り替え→500</string>\r\n  <string>ブラシ 4304 補正S→0</string>\r\n  <string>ブラシ 4305 補正S→" +
            "5</string>\r\n  <string>ブラシ 4306 補正S→10</string>\r\n  <string>ブラシ 4307 補正S→15</strin" +
            "g>\r\n  <string>ブラシ 4308 補正S→20</string>\r\n  <string>α 4320 SIMDを使用しない</string>\r\n  " +
            "<string>α 4324 SSE2を使用する</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AllKeyDef {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllKeyDef"]));
            }
        }
        
        /// <summary>
        /// 修飾キーボタンのポップアップに表示する文字列
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("修飾キーボタンのポップアップに表示する文字列")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>リセット</string>
  <string>Ctrl</string>
  <string>Shift</string>
  <string>Alt</string>
  <string>Space</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModStr {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModStr"]));
            }
            set {
                this["ModStr"] = value;
            }
        }
        
        /// <summary>
        /// 修飾キーボタンキー割り当て
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("修飾キーボタンキー割り当て")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>Ctrl</string>
  <string>Shift</string>
  <string>Alt</string>
  <string>Space</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ModCD {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ModCD"]));
            }
            set {
                this["ModCD"] = value;
            }
        }
        
        /// <summary>
        /// ネコペのショートカット番号でのキー割り当て(5個1セット)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("ネコペのショートカット番号でのキー割り当て(5個1セット)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>769</string>
  <string>787</string>
  <string>785</string>
  <string>786</string>
  <string>770</string>
  <string>3073</string>
  <string>3120</string>
  <string>3104</string>
  <string>3136</string>
  <string>3074</string>
  <string>2838</string>
  <string>2834</string>
  <string>2835</string>
  <string>3122</string>
  <string>2848</string>
  <string>3105</string>
  <string>1538</string>
  <string>3106</string>
  <string>788 </string>
  <string>1537</string>
  <string>1281</string>
  <string>1283</string>
  <string>1362</string>
  <string>1284</string>
  <string>1282</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeyCDNP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeyCDNP"]));
            }
            set {
                this["KeyCDNP"] = value;
            }
        }
        
        /// <summary>
        /// マクロ名によるホイール機能割当
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("マクロ名によるホイール機能割当")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string />
  <string>nFrick.nas bprm_up2</string>
  <string>nFrick.nas bprm_down2</string>
  <string>nFrick.nas bprm_up1</string>
  <string>nFrick.nas bprm_down1</string>
  <string>nFrick.nas bprm_up48</string>
  <string>nFrick.nas bprm_down48</string>
  <string>nFrick.nas nl_opa_up</string>
  <string>nFrick.nas nl_opa_down</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection padCDNP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["padCDNP"]));
            }
            set {
                this["padCDNP"] = value;
            }
        }
        
        /// <summary>
        /// マクロ名によるホイール機能割当(逆回転)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("マクロ名によるホイール機能割当(逆回転)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>nFrick.nas bprm_down2</string>
  <string>nFrick.nas bprm_down1</string>
  <string>nFrick.nas bprm_down48</string>
  <string>nFrick.nas nl_opa_down</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection padCDNPR {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["padCDNPR"]));
            }
            set {
                this["padCDNPR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUpgrade {
            get {
                return ((bool)(this["IsUpgrade"]));
            }
            set {
                this["IsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"b.bitmap_file=円3
b.bitmap_folder=|b.color=|b.layer=|b.n1=1.17994864883731|b.n10=1
b.n100=|b.n11=1|b.n12=1|b.n13=0|b.n14=0
b.n15=1|b.n16=2|b.n17=0|b.n18=0|b.n2=246
b.n201=|b.n202=|b.n203=|b.n204=0 0 4096 0|b.n205=0 0 4096 0
b.n21=0|b.n22=1|b.n23=0|b.n24=0|b.n25=0
b.n26=100|b.n27=0|b.n28=0|b.n29=0|b.n3=55.7762461302863
b.n30=1|b.n31=0|b.n32=0|b.n33=0|b.n34=1
b.n35=0|b.n36=1|b.n37=4|b.n38=140|b.n39=0
b.n4=0|b.n40=0|b.n41=0|b.n42=1|b.n43=0
b.n44=1|b.n45=4|b.n46=0|b.n48=256|b.n49=0
b.n5=0|b.n50=0|b.n51=256|b.n52=0|b.n53=0
b.n54=0|b.n55=0|b.n56=0|b.n57=0|b.n58=0
b.n59=0|b.n6=0|b.n60=1.29062024949075E-306|b.n61=4.24391670529379E-314|b.n8=通常
""b.texture_file=|b.texture_folder=|b.tool=""
")]
        public string brsPrm {
            get {
                return ((string)(this["brsPrm"]));
            }
            set {
                this["brsPrm"] = value;
            }
        }
    }
}
